services:
  garden-mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - garden-mongo-data:/data/db
    networks:
      - internal

  garden-api:
    build: ./api
    restart: unless-stopped
    env_file: .env
    depends_on:
      - garden-mongo
    networks:
      - traefik-public
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.garden-api.rule=Host(`garden.jammin-dev.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.garden-api.entrypoints=websecure"
      - "traefik.http.routers.garden-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.garden-api.loadbalancer.server.port=8000"

  garden-frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: https://garden.jammin-dev.com/api/v1/
    restart: unless-stopped
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.garden-frontend.rule=Host(`garden.jammin-dev.com`)"
      - "traefik.http.routers.garden-frontend.entrypoints=websecure"
      - "traefik.http.routers.garden-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.garden-frontend.loadbalancer.server.port=80"

volumes:
  garden-mongo-data:

networks:
  traefik-public:
    external: true
  internal:
    driver: bridge
