export const action_names =  {
    SOWING : "SOWING",
    PLANTING: "PLANTING",
    REMOVING: "REMOVING",
    WATERING: "WATERING",
    FERTILIZING: "FERTILIZING",
    TREATING: "TREATING",
    HARVESTING: "HARVESTING",
    WEEDING: "WEEDING",
    OBSERVING: "OBSERVING",
  }

export const ACCESS_TOKEN =  "JWTGP"